# version: '3.3'
services:
  front:
    image: front-img
    container_name: front-container
    build: ./front
    ports:
      - 3000:3000
    networks:
      - wannup-test-network
    volumes:
      - ./front:/app
    # env_file:
    #   - .env
    restart: always

  # back:
  #   image: back-img
  #   container_name: back-container
  #   ports:
  #     - 8000:8000
  #   networks:
  #     - wannup-test-network
  #   volumes:
  #     - ./back:/dev/app
  #   env_file:
  #     - .env
  #   restart: always
  #   build: ./back

networks:
  wannup-test-network:
    driver: bridge
